/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatesRouteImport } from './routes/states'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesStateRouteImport } from './routes/states.$state'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AuctionsIdRouteImport } from './routes/auctions.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardWonRouteImport } from './routes/_authenticated/dashboard.won'
import { Route as AuthenticatedDashboardWatchedRouteImport } from './routes/_authenticated/dashboard.watched'
import { Route as AuthenticatedDashboardSearchesRouteImport } from './routes/_authenticated/dashboard.searches'
import { Route as AuthenticatedDashboardScheduledRouteImport } from './routes/_authenticated/dashboard.scheduled'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardLostRouteImport } from './routes/_authenticated/dashboard.lost'
import { Route as AuthenticatedDashboardHistoryRouteImport } from './routes/_authenticated/dashboard.history'
import { Route as AuthenticatedDashboardFundsRouteImport } from './routes/_authenticated/dashboard.funds'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard.documents'
import { Route as AuthenticatedDashboardBidsRouteImport } from './routes/_authenticated/dashboard.bids'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin.registrations'
import { Route as AuthenticatedAdminPropertiesRouteImport } from './routes/_authenticated/admin.properties'
import { Route as AuthenticatedAdminLiensRouteImport } from './routes/_authenticated/admin.liens'
import { Route as AuthenticatedAdminFundsRouteImport } from './routes/_authenticated/admin.funds'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminCountiesRouteImport } from './routes/_authenticated/admin.counties'
import { Route as AuthenticatedAdminBidsRouteImport } from './routes/_authenticated/admin.bids'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAuctionsRouteImport } from './routes/_authenticated/admin.auctions'

const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateRoute = StatesStateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => StatesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardWonRoute =
  AuthenticatedDashboardWonRouteImport.update({
    id: '/won',
    path: '/won',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWatchedRoute =
  AuthenticatedDashboardWatchedRouteImport.update({
    id: '/watched',
    path: '/watched',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSearchesRoute =
  AuthenticatedDashboardSearchesRouteImport.update({
    id: '/searches',
    path: '/searches',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardScheduledRoute =
  AuthenticatedDashboardScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLostRoute =
  AuthenticatedDashboardLostRouteImport.update({
    id: '/lost',
    path: '/lost',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHistoryRoute =
  AuthenticatedDashboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFundsRoute =
  AuthenticatedDashboardFundsRouteImport.update({
    id: '/funds',
    path: '/funds',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBidsRoute =
  AuthenticatedDashboardBidsRouteImport.update({
    id: '/bids',
    path: '/bids',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPropertiesRoute =
  AuthenticatedAdminPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiensRoute = AuthenticatedAdminLiensRouteImport.update({
  id: '/liens',
  path: '/liens',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFundsRoute = AuthenticatedAdminFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountiesRoute =
  AuthenticatedAdminCountiesRouteImport.update({
    id: '/counties',
    path: '/counties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBidsRoute = AuthenticatedAdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuctionsRoute =
  AuthenticatedAdminAuctionsRouteImport.update({
    id: '/auctions',
    path: '/auctions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/states/$state': typeof StatesStateRoute
  '/admin/auctions': typeof AuthenticatedAdminAuctionsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bids': typeof AuthenticatedAdminBidsRoute
  '/admin/counties': typeof AuthenticatedAdminCountiesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/liens': typeof AuthenticatedAdminLiensRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/bids': typeof AuthenticatedDashboardBidsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/lost': typeof AuthenticatedDashboardLostRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/scheduled': typeof AuthenticatedDashboardScheduledRoute
  '/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/dashboard/watched': typeof AuthenticatedDashboardWatchedRoute
  '/dashboard/won': typeof AuthenticatedDashboardWonRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/states/$state': typeof StatesStateRoute
  '/admin/auctions': typeof AuthenticatedAdminAuctionsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bids': typeof AuthenticatedAdminBidsRoute
  '/admin/counties': typeof AuthenticatedAdminCountiesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/admin/liens': typeof AuthenticatedAdminLiensRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/bids': typeof AuthenticatedDashboardBidsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/lost': typeof AuthenticatedDashboardLostRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/scheduled': typeof AuthenticatedDashboardScheduledRoute
  '/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/dashboard/watched': typeof AuthenticatedDashboardWatchedRoute
  '/dashboard/won': typeof AuthenticatedDashboardWonRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/states': typeof StatesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auctions/$id': typeof AuctionsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/states/$state': typeof StatesStateRoute
  '/_authenticated/admin/auctions': typeof AuthenticatedAdminAuctionsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bids': typeof AuthenticatedAdminBidsRoute
  '/_authenticated/admin/counties': typeof AuthenticatedAdminCountiesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/funds': typeof AuthenticatedAdminFundsRoute
  '/_authenticated/admin/liens': typeof AuthenticatedAdminLiensRoute
  '/_authenticated/admin/properties': typeof AuthenticatedAdminPropertiesRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/bids': typeof AuthenticatedDashboardBidsRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/funds': typeof AuthenticatedDashboardFundsRoute
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/_authenticated/dashboard/lost': typeof AuthenticatedDashboardLostRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/scheduled': typeof AuthenticatedDashboardScheduledRoute
  '/_authenticated/dashboard/searches': typeof AuthenticatedDashboardSearchesRoute
  '/_authenticated/dashboard/watched': typeof AuthenticatedDashboardWatchedRoute
  '/_authenticated/dashboard/won': typeof AuthenticatedDashboardWonRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/how-it-works'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/admin'
    | '/dashboard'
    | '/auctions/$id'
    | '/properties/$id'
    | '/states/$state'
    | '/admin/auctions'
    | '/admin/audit'
    | '/admin/bids'
    | '/admin/counties'
    | '/admin/documents'
    | '/admin/funds'
    | '/admin/liens'
    | '/admin/properties'
    | '/admin/registrations'
    | '/admin/users'
    | '/dashboard/bids'
    | '/dashboard/documents'
    | '/dashboard/funds'
    | '/dashboard/history'
    | '/dashboard/lost'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/scheduled'
    | '/dashboard/searches'
    | '/dashboard/watched'
    | '/dashboard/won'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/how-it-works'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/auctions/$id'
    | '/properties/$id'
    | '/states/$state'
    | '/admin/auctions'
    | '/admin/audit'
    | '/admin/bids'
    | '/admin/counties'
    | '/admin/documents'
    | '/admin/funds'
    | '/admin/liens'
    | '/admin/properties'
    | '/admin/registrations'
    | '/admin/users'
    | '/dashboard/bids'
    | '/dashboard/documents'
    | '/dashboard/funds'
    | '/dashboard/history'
    | '/dashboard/lost'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/scheduled'
    | '/dashboard/searches'
    | '/dashboard/watched'
    | '/dashboard/won'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/how-it-works'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/states'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/auctions/$id'
    | '/properties/$id'
    | '/states/$state'
    | '/_authenticated/admin/auctions'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bids'
    | '/_authenticated/admin/counties'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/funds'
    | '/_authenticated/admin/liens'
    | '/_authenticated/admin/properties'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/bids'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/funds'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/lost'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/scheduled'
    | '/_authenticated/dashboard/searches'
    | '/_authenticated/dashboard/watched'
    | '/_authenticated/dashboard/won'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuctionsRoute: typeof AuctionsRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatesRoute: typeof StatesRouteWithChildren
  PropertiesIdRoute: typeof PropertiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$state': {
      id: '/states/$state'
      path: '/$state'
      fullPath: '/states/$state'
      preLoaderRoute: typeof StatesStateRouteImport
      parentRoute: typeof StatesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/won': {
      id: '/_authenticated/dashboard/won'
      path: '/won'
      fullPath: '/dashboard/won'
      preLoaderRoute: typeof AuthenticatedDashboardWonRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/watched': {
      id: '/_authenticated/dashboard/watched'
      path: '/watched'
      fullPath: '/dashboard/watched'
      preLoaderRoute: typeof AuthenticatedDashboardWatchedRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/searches': {
      id: '/_authenticated/dashboard/searches'
      path: '/searches'
      fullPath: '/dashboard/searches'
      preLoaderRoute: typeof AuthenticatedDashboardSearchesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/scheduled': {
      id: '/_authenticated/dashboard/scheduled'
      path: '/scheduled'
      fullPath: '/dashboard/scheduled'
      preLoaderRoute: typeof AuthenticatedDashboardScheduledRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/lost': {
      id: '/_authenticated/dashboard/lost'
      path: '/lost'
      fullPath: '/dashboard/lost'
      preLoaderRoute: typeof AuthenticatedDashboardLostRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/funds': {
      id: '/_authenticated/dashboard/funds'
      path: '/funds'
      fullPath: '/dashboard/funds'
      preLoaderRoute: typeof AuthenticatedDashboardFundsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bids': {
      id: '/_authenticated/dashboard/bids'
      path: '/bids'
      fullPath: '/dashboard/bids'
      preLoaderRoute: typeof AuthenticatedDashboardBidsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties': {
      id: '/_authenticated/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/liens': {
      id: '/_authenticated/admin/liens'
      path: '/liens'
      fullPath: '/admin/liens'
      preLoaderRoute: typeof AuthenticatedAdminLiensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funds': {
      id: '/_authenticated/admin/funds'
      path: '/funds'
      fullPath: '/admin/funds'
      preLoaderRoute: typeof AuthenticatedAdminFundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/counties': {
      id: '/_authenticated/admin/counties'
      path: '/counties'
      fullPath: '/admin/counties'
      preLoaderRoute: typeof AuthenticatedAdminCountiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bids': {
      id: '/_authenticated/admin/bids'
      path: '/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AuthenticatedAdminBidsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auctions': {
      id: '/_authenticated/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AuthenticatedAdminAuctionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuctionsRoute: typeof AuthenticatedAdminAuctionsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBidsRoute: typeof AuthenticatedAdminBidsRoute
  AuthenticatedAdminCountiesRoute: typeof AuthenticatedAdminCountiesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFundsRoute: typeof AuthenticatedAdminFundsRoute
  AuthenticatedAdminLiensRoute: typeof AuthenticatedAdminLiensRoute
  AuthenticatedAdminPropertiesRoute: typeof AuthenticatedAdminPropertiesRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuctionsRoute: AuthenticatedAdminAuctionsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBidsRoute: AuthenticatedAdminBidsRoute,
  AuthenticatedAdminCountiesRoute: AuthenticatedAdminCountiesRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminFundsRoute: AuthenticatedAdminFundsRoute,
  AuthenticatedAdminLiensRoute: AuthenticatedAdminLiensRoute,
  AuthenticatedAdminPropertiesRoute: AuthenticatedAdminPropertiesRoute,
  AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBidsRoute: typeof AuthenticatedDashboardBidsRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardFundsRoute: typeof AuthenticatedDashboardFundsRoute
  AuthenticatedDashboardHistoryRoute: typeof AuthenticatedDashboardHistoryRoute
  AuthenticatedDashboardLostRoute: typeof AuthenticatedDashboardLostRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardScheduledRoute: typeof AuthenticatedDashboardScheduledRoute
  AuthenticatedDashboardSearchesRoute: typeof AuthenticatedDashboardSearchesRoute
  AuthenticatedDashboardWatchedRoute: typeof AuthenticatedDashboardWatchedRoute
  AuthenticatedDashboardWonRoute: typeof AuthenticatedDashboardWonRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBidsRoute: AuthenticatedDashboardBidsRoute,
    AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
    AuthenticatedDashboardFundsRoute: AuthenticatedDashboardFundsRoute,
    AuthenticatedDashboardHistoryRoute: AuthenticatedDashboardHistoryRoute,
    AuthenticatedDashboardLostRoute: AuthenticatedDashboardLostRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardScheduledRoute: AuthenticatedDashboardScheduledRoute,
    AuthenticatedDashboardSearchesRoute: AuthenticatedDashboardSearchesRoute,
    AuthenticatedDashboardWatchedRoute: AuthenticatedDashboardWatchedRoute,
    AuthenticatedDashboardWonRoute: AuthenticatedDashboardWonRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuctionsRouteChildren {
  AuctionsIdRoute: typeof AuctionsIdRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsIdRoute: AuctionsIdRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

interface StatesRouteChildren {
  StatesStateRoute: typeof StatesStateRoute
}

const StatesRouteChildren: StatesRouteChildren = {
  StatesStateRoute: StatesStateRoute,
}

const StatesRouteWithChildren =
  StatesRoute._addFileChildren(StatesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuctionsRoute: AuctionsRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatesRoute: StatesRouteWithChildren,
  PropertiesIdRoute: PropertiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
